// solid-ads/src/Article.tsx
import type { Component } from "solid-js";
import { AdSlotRight } from "./AdSlotRight";
import { Lorem } from "./Lorem";

const articleLayout = {
  display: "grid",
  "grid-area": "article",
  "grid-template": '"articlel article articler"',
  gap: "2rem",
  "grid-template-columns": "220px auto 300px",
  "border-left": "1px solid lightgrey",
  "border-right": "1px solid lightgrey",
  "padding-right": "2rem",
};

export const Article: Component = () => {
  return (
    <div style={articleLayout}>
      <div
        style={{
          "grid-area": "articlel",
          "padding-left": "1rem",
          "padding-top": "0.5rem",
        }}
      >
        <div
          style={{
            "font-size": "1.25rem",
            color: "#C70000",
            "font-weight": 700,
          }}
        >
          Commercial Dev
        </div>
      </div>
      <div
        style={{
          "grid-area": "article",
          "border-left": "1px solid lightgrey",
          "padding-left": "1rem",
        }}
      >
        <div style={{ "font-size": "2.5rem" }}>Something about something</div>
        <Lorem />
      </div>
      <div style={{ "grid-area": "articler" }}>
        <AdSlotRight />
      </div>
    </div>
  );
};

// src/Article.tsx
import React from 'react';
import { AdSlotRight } from './AdSlotRight';
import { Lorem } from './Lorem';

const articleLayout = {
    display: 'grid',
    gridArea: 'article',
    gridTemplate: '"articlel article articler"',
    gap: '2rem',
    gridTemplateColumns: '220px auto 300px',
    borderLeft: '1px solid lightgrey',
    borderRight: '1px solid lightgrey',
    paddingRight: '2rem',
};

const Article = () => {
    return (
        <div style={articleLayout}>
            <div style={{ gridArea: 'articlel' }}></div>
            <div style={{ gridArea: 'article', borderLeft: '1px solid lightgrey', paddingLeft: '1rem' }}>
                <Lorem />
            </div>
            <div style={{ gridArea: 'articler' }}>
                <AdSlotRight />
            </div>
        </div>
    )
};

export { Article };
