// src/Nav.tsx
import React from "react";

const Nav = () => {
    return (
        <div style={{
            backgroundColor: '#052966',
            gridArea: 'nav',
            position: 'relative'
        }}>
            <div style={{ position: 'absolute', right: '4rem' }}>
                <img src='/adian.png' width='360px' height='auto'></img>
            </div>
        </div>
    )
}

export { Nav }

// solid-ads/src/Nav.tsx
import type { Component } from "solid-js";

export const Nav: Component = () => {
  return (
    <div
      style={{
        "background-color": "#052966",
        "grid-area": "nav",
        position: "relative",
      }}
    >
      <div style={{ position: "absolute", right: "4rem" }}>
        <img src="/adian.png" width="360px" height="auto"></img>
      </div>
    </div>
  );
};
